fix: changing templates apiVersion to be compatible with OCP 4.11
Running `oc create -f` targeting any of the yaml files raised the following error:

> error: resource mapping not found for name: "<...>" namespace: "" from "<...>.yaml": **no matches for kind "Template" in version "v1"**

Solution: changing from v1 to [template.openshift.io/v1](https://docs.openshift.com/container-platform/4.11/rest_api/template_apis/template-template-openshift-io-v1.html)